<?php

namespace Homeful\Contacts\Enums;

use Homeful\Common\Traits\EnumUtils;
use Homeful\Contacts\Traits\HasCode;

enum Nationality: string
{
    use EnumUtils;
    use HasCode;

    case AFGHAN = 'Afghan';
    case ALBANIAN = 'Albanian';
    case ALGERIAN = 'Algerian';
    case AMERICAN = 'American';
    case ANDORRAN = 'Andorran';
    case ANGOLAN = 'Angolan';
    case ANGUILLAN = 'Anguillan';
    case ARGENTINE = 'Argentine';
    case ARMENIAN = 'Armenian';
    case AUSTRALIAN = 'Australian';
    case AUSTRIAN = 'Austrian';
    case AZERBAIJANI = 'Azerbaijani';
    case BAHAMIAN = 'Bahamian';
    case BAHRAINI = 'Bahraini';
    case BANGLADESHI = 'Bangladeshi';
    case BARBADIAN = 'Barbadian';
    case BELARUSIAN = 'Belarusian';
    case BELGIAN = 'Belgian';
    case BELIZEAN = 'Belizean';
    case BENINESE = 'Beninese';
    case BERMUDIAN = 'Bermudian';
    case BHUTANESE = 'Bhutanese';
    case BOLIVIAN = 'Bolivian';
    case BOTSWANAN = 'Botswanan';
    case BRAZILIAN = 'Brazilian';
    case BRITISH = 'British';
    case BRITISH_VIRGIN_ISLANDER = 'British Virgin Islander';
    case BRUNEIAN = 'Bruneian';
    case BULGARIAN = 'Bulgarian';
    case BURKINAN = 'Burkinan';
    case BURMESE = 'Burmese';
    case BURUNDIAN = 'Burundian';
    case CAMBODIAN = 'Cambodian';
    case CAMEROONIAN = 'Cameroonian';
    case CANADIAN = 'Canadian';
    case CAPE_VERDEAN = 'Cape Verdean';
    case CAYMAN_ISLANDER = 'Cayman Islander';
    case CENTRAL_AFRICAN = 'Central African';
    case CHADIAN = 'Chadian';
    case CHILEAN = 'Chilean';
    case CHINESE = 'Chinese';
    case CITIZEN_OF_ANTIGUA_AND_BARBUDA = 'Citizen of Antigua and Barbuda';
    case CITIZEN_OF_BOSNIA_AND_HERZEGOVINA = 'Citizen of Bosnia and Herzegovina';
    case CITIZEN_OF_GUINEA_BISSAU = 'Citizen of Guinea-Bissau';
    case CITIZEN_OF_KIRIBATI = 'Citizen of Kiribati';
    case CITIZEN_OF_SEYCHELLES = 'Citizen of Seychelles';
    case CITIZEN_OF_THE_DOMINICAN_REPUBLIC = 'Citizen of the Dominican Republic';
    case CITIZEN_OF_VANUATU = 'Citizen of Vanuatu';
    case COLOMBIAN = 'Colombian';
    case COMORAN = 'Comoran';
    case CONGOLESE_CONGO = 'Congolese (Congo)';
    case CONGOLESE_DRC = 'Congolese (DRC)';
    case COOK_ISLANDER = 'Cook Islander';
    case COSTA_RICAN = 'Costa Rican';
    case CROATIAN = 'Croatian';
    case CUBAN = 'Cuban';
    case CYMRAES = 'Cymraes';
    case CYMRO = 'Cymro';
    case CYPRIOT = 'Cypriot';
    case CZECH = 'Czech';
    case DANISH = 'Danish';
    case DJIBOUTIAN = 'Djiboutian';
    case DOMINICAN = 'Dominican';
    case DUTCH = 'Dutch';
    case EAST_TIMORESE = 'East Timorese';
    case ECUADOREAN = 'Ecuadorian';
    case EGYPTIAN = 'Egyptian';
    case EMIRATI = 'Emirati';
    case ENGLISH = 'English';
    case EQUATORIAL_GUINEAN = 'Equatorial Guinean';
    case ERITREAN = 'Eritrean';
    case ESTONIAN = 'Estonian';
    case ETHIOPIAN = 'Ethiopian';
    case FAROESE = 'Faroese';
    case FIJIAN = 'Fijian';
    case FILIPINO = 'Filipino';
    case FINNISH = 'Finnish';
    case FRENCH = 'French';
    case GABONESE = 'Gabonese';
    case GAMBIAN = 'Gambian';
    case GEORGIAN = 'Georgian';
    case GERMAN = 'German';
    case GHANAIAN = 'Ghanaian';
    case GIBRALTARIAN = 'Gibraltarian';
    case GREEK = 'Greek';
    case GREENLANDIC = 'Greenlandic';
    case GRENADIAN = 'Grenadian';
    case GUAMANIAN = 'Guamanian';
    case GUATEMALAN = 'Guatemalan';
    case GUINEAN = 'Guinean';
    case GUYANESE = 'Guyanese';
    case HAITIAN = 'Haitian';
    case HONDURAN = 'Honduran';
    case HONG_KONGER = 'Hong Konger';
    case HUNGARIAN = 'Hungarian';
    case ICELANDIC = 'Icelandic';
    case INDIAN = 'Indian';
    case INDONESIAN = 'Indonesian';
    case IRANIAN = 'Iranian';
    case IRAQI = 'Iraqi';
    case IRISH = 'Irish';
    case ISRAELI = 'Israeli';
    case ITALIAN = 'Italian';
    case IVORIAN = 'Ivorian';
    case JAMAICAN = 'Jamaican';
    case JAPANESE = 'Japanese';
    case JORDANIAN = 'Jordanian';
    case KAZAKH = 'Kazakh';
    case KENYAN = 'Kenyan';
    case KITTITIAN = 'Kittitian';
    case KOSOVAN = 'Kosovan';
    case KUWAITI = 'Kuwaiti';
    case KYRGYZ = 'Kyrgyz';
    case LAO = 'Lao';
    case LATVIAN = 'Latvian';
    case LEBANESE = 'Lebanese';
    case LIBERIAN = 'Liberian';
    case LIBYAN = 'Libyan';
    case LIECHTENSTEIN_CITIZEN = 'Liechtenstein citizen';
    case LITHUANIAN = 'Lithuanian';
    case LUXEMBOURGER = 'Luxembourger';
    case MACANESE = 'Macanese';
    case MACEDONIAN = 'Macedonian';
    case MALAGASY = 'Malagasy';
    case MALAWIAN = 'Malawian';
    case MALAYSIAN = 'Malaysian';
    case MALDIVIAN = 'Maldivian';
    case MALIAN = 'Malian';
    case MALTESE = 'Maltese';
    case MARSHALLESE = 'Marshallese';
    case MARTINIQUAIS = 'Martiniquais';
    case MAURITANIAN = 'Mauritanian';
    case MAURITIAN = 'Mauritian';
    case MEXICAN = 'Mexican';
    case MICRONESIAN = 'Micronesian';
    case MOLDOVAN = 'Moldovan';
    case MONEGASQUE = 'Monegasque';
    case MONGOLIAN = 'Mongolian';
    case MONTENEGRIN = 'Montenegrin';
    case MONTSERRATIAN = 'Montserratian';
    case MOROCCAN = 'Moroccan';
    case MOSOTHO = 'Mosotho';
    case MOZAMBICAN = 'Mozambican';
    case NAMIBIAN = 'Namibian';
    case NAURUAN = 'Nauruan';
    case NEPALESE = 'Nepalese';
    case NEW_ZEALANDER = 'New Zealander';
    case NICARAGUAN = 'Nicaraguan';
    case NIGERIAN = 'Nigerian';
    case NIGERIEN = 'Nigerien';
    case NIUEAN = 'Niuean';
    case NORTH_KOREAN = 'North Korean';
    case NORTHERN_IRISH = 'Northern Irish';
    case NORWEGIAN = 'Norwegian';
    case OMANI = 'Omani';
    case PAKISTANI = 'Pakistani';
    case PALAUAN = 'Palauan';
    case PALESTINIAN = 'Palestinian';
    case PANAMANIAN = 'Panamanian';
    case PAPUA_NEW_GUINEAN = 'Papua New Guinean';
    case PARAGUAYAN = 'Paraguayan';
    case PERUVIAN = 'Peruvian';
    case PITCAIRN_ISLANDER = 'Pitcairn Islander';
    case POLISH = 'Polish';
    case PORTUGUESE = 'Portuguese';
    case PRYDEINIG = 'Prydeinig';
    case PUERTO_RICAN = 'Puerto Rican';
    case QATARI = 'Qatari';
    case ROMANIAN = 'Romanian';
    case RUSSIAN = 'Russian';
    case RWANDAN = 'Rwandan';
    case SALVADOREAN = 'Salvadorean';
    case SAMMARINESE = 'Sammarinese';
    case SAMOAN = 'Samoan';
    case SAO_TOMEAN = 'Sao Tomean';
    case SAUDI_ARABIAN = 'Saudi Arabian';
    case SCOTTISH = 'Scottish';
    case SENEGALese = 'Senegalese';
    case SERBIAN = 'Serbian';
    case SIERRA_LEONEAN = 'Sierra Leonean';
    case SINGAPOREAN = 'Singaporean';
    case SLOVAK = 'Slovak';
    case SLOVENIAN = 'Slovenian';
    case SOLOMON_ISLANDER = 'Solomon Islander';
    case SOMALI = 'Somali';
    case SOUTH_AFRICAN = 'South African';
    case SOUTH_KOREAN = 'South Korean';
    case SOUTH_SUDANESE = 'South Sudanese';
    case SPANISH = 'Spanish';
    case SRI_LANKAN = 'Sri Lankan';
    case ST_HELENIAN = 'St Helenian';
    case ST_LUCIAN = 'St Lucian';
    case STATELESS = 'Stateless';
    case SUDANESE = 'Sudanese';
    case SURINAMESE = 'Surinamese';
    case SWAZI = 'Swazi';
    case SWEDISH = 'Swedish';
    case SWISS = 'Swiss';

    static function default(): self {
        return self::FILIPINO;
    }

    public function code(): string
    {
        return match ($this) {
            self::AFGHAN => '1',
            self::ALBANIAN => '2',
            self::ALGERIAN => '3',
            self::AMERICAN => '4',
            self::ANDORRAN => '5',
            self::ANGOLAN => '6',
            self::ANGUILLAN => '7',
            self::ARGENTINE => '8',
            self::ARMENIAN => '9',
            self::AUSTRALIAN => '10',
            self::AUSTRIAN => '11',
            self::AZERBAIJANI => '12',
            self::BAHAMIAN => '13',
            self::BAHRAINI => '14',
            self::BANGLADESHI => '15',
            self::BARBADIAN => '16',
            self::BELARUSIAN => '17',
            self::BELGIAN => '18',
            self::BELIZEAN => '19',
            self::BENINESE => '20',
            self::BERMUDIAN => '21',
            self::BHUTANESE => '22',
            self::BOLIVIAN => '23',
            self::BOTSWANAN => '24',
            self::BRAZILIAN => '25',
            self::BRITISH => '26',
            self::BRITISH_VIRGIN_ISLANDER => '27',
            self::BRUNEIAN => '28',
            self::BULGARIAN => '29',
            self::BURKINAN => '30',
            self::BURMESE => '31',
            self::BURUNDIAN => '32',
            self::CAMBODIAN => '33',
            self::CAMEROONIAN => '34',
            self::CANADIAN => '35',
            self::CAPE_VERDEAN => '36',
            self::CAYMAN_ISLANDER => '37',
            self::CENTRAL_AFRICAN => '38',
            self::CHADIAN => '39',
            self::CHILEAN => '40',
            self::CHINESE => '41',
            self::CITIZEN_OF_ANTIGUA_AND_BARBUDA => '42',
            self::CITIZEN_OF_BOSNIA_AND_HERZEGOVINA => '43',
            self::CITIZEN_OF_GUINEA_BISSAU => '44',
            self::CITIZEN_OF_KIRIBATI => '45',
            self::CITIZEN_OF_SEYCHELLES => '46',
            self::CITIZEN_OF_THE_DOMINICAN_REPUBLIC => '47',
            self::CITIZEN_OF_VANUATU => '48',
            self::COLOMBIAN => '49',
            self::COMORAN => '50',
            self::CONGOLESE_CONGO => '51',
            self::CONGOLESE_DRC => '52',
            self::COOK_ISLANDER => '53',
            self::COSTA_RICAN => '54',
            self::CROATIAN => '55',
            self::CUBAN => '56',
            self::CYMRAES => '57',
            self::CYMRO => '58',
            self::CYPRIOT => '59',
            self::CZECH => '60',
            self::DANISH => '61',
            self::DJIBOUTIAN => '62',
            self::DOMINICAN => '63',
            self::DUTCH => '64',
            self::EAST_TIMORESE => '65',
            self::ECUADOREAN => '66',
            self::EGYPTIAN => '67',
            self::EMIRATI => '68',
            self::ENGLISH => '69',
            self::EQUATORIAL_GUINEAN => '70',
            self::ERITREAN => '71',
            self::ESTONIAN => '72',
            self::ETHIOPIAN => '73',
            self::FAROES => '74',
            self::FIJIAN => '75',
            self::FILIPINO => '76',
            self::FINNISH => '77',
            self::FRENCH => '78',
            self::GABONESE => '79',
            self::GAMBIAN => '80',
            self::GEORGIAN => '81',
            self::GERMAN => '82',
            self::GHANAIAN => '83',
            self::GIBRALTARIAN => '84',
            self::GREEK => '85',
            self::GREENLANDIC => '86',
            self::GRENADIAN => '87',
            self::GUAMANIAN => '88',
            self::GUATEMALAN => '89',
            self::GUINEAN => '90',
            self::GUYANESE => '91',
            self::HAITIAN => '92',
            self::HONDURAN => '93',
            self::HONG_KONGER => '94',
            self::HUNGARIAN => '95',
            self::ICELANDIC => '96',
            self::INDIAN => '97',
            self::INDONESIAN => '98',
            self::IRANIAN => '99',
            self::IRAQI => '100',
            self::IRISH => '101',
            self::ISRAELI => '102',
            self::ITALIAN => '103',
            self::IVORIAN => '104',
            self::JAMAICAN => '105',
            self::JAPANESE => '106',
            self::JORDANIAN => '107',
            self::KAZAKH => '108',
            self::KENYAN => '109',
            self::KITTITIAN => '110',
            self::KOSOVAN => '111',
            self::KUWAITI => '112',
            self::KYRGYZ => '113',
            self::LAO => '114',
            self::LATVIAN => '115',
            self::LEBANESE => '116',
            self::LIBERIAN => '117',
            self::LIBYAN => '118',
            self::LIECHTENSTEIN_CITIZEN => '119',
            self::LITHUANIAN => '120',
            self::LUXEMBOURGER => '121',
            self::MACANESE => '122',
            self::MACEDONIAN => '123',
            self::MALAGASY => '124',
            self::MALAWIAN => '125',
            self::MALAYSIAN => '126',
            self::MALDIVIAN => '127',
            self::MALIAN => '128',
            self::MALTESE => '129',
            self::MARSHALLESE => '130',
            self::MARTINIQUAIS => '131',
            self::MAURITANIAN => '132',
            self::MAURITIAN => '133',
            self::MEXICAN => '134',
            self::MICRONESIAN => '135',
            self::MOLDOVAN => '136',
            self::MONEGASQUE => '137',
            self::MONGOLIAN => '138',
            self::MONTENEGRIN => '139',
            self::MONTSERRATIAN => '140',
            self::MOROCCAN => '141',
            self::MOSOTHO => '142',
            self::MOZAMBICAN => '143',
            self::NAMIBIAN => '144',
            self::NAURUAN => '145',
            self::NEPALESE => '146',
            self::NEW_ZEALANDER => '147',
            self::NICARAGUAN => '148',
            self::NIGERIAN => '149',
            self::NIGERIEN => '150',
            self::NIUEAN => '151',
            self::NORTH_KOREAN => '152',
            self::NORTHERN_IRISH => '153',
            self::NORWEGIAN => '154',
            self::OMANI => '155',
            self::PAKISTANI => '156',
            self::PALAUAN => '157',
            self::PALESTINIAN => '158',
            self::PANAMANIAN => '159',
            self::PAPUA_NEW_GUINEAN => '160',
            self::PARAGUAYAN => '161',
            self::PERUVIAN => '162',
            self::PITCAIRN_ISLANDER => '163',
            self::POLISH => '164',
            self::PORTUGUESE => '165',
            self::PRYDEINIG => '166',
            self::PUERTO_RICAN => '167',
            self::QATARI => '168',
            self::ROMANIAN => '169',
            self::RUSSIAN => '170',
            self::RWANDAN => '171',
            self::SALVADOREAN => '172',
            self::SAMMARINESE => '173',
            self::SAMOAN => '174',
            self::SAO_TOMEAN => '175',
            self::SAUDI_ARABIAN => '176',
            self::SCOTTISH => '177',
            self::SENEGALESE => '178',
            self::SERBIAN => '179',
            self::SIERRA_LEONEAN => '180',
            self::SINGAPOREAN => '181',
            self::SLOVAK => '182',
            self::SLOVENIAN => '183',
            self::SOLOMON_ISLANDER => '184',
            self::SOMALI => '185',
            self::SOUTH_AFRICAN => '186',
            self::SOUTH_KOREAN => '187',
            self::SOUTH_SUDANESE => '188',
            self::SPANISH => '189',
            self::SRI_LANKAN => '190',
            self::ST_HELENIAN => '191',
            self::ST_LUCIAN => '192',
            self::STATELESS => '193',
            self::SUDANESE => '194',
            self::SURINAMESE => '195',
            self::SWAZI => '196',
            self::SWEDISH => '197',
            self::SWISS => '198',
        };
    }
}
