<?php

namespace Homeful\Contacts\Enums;

use Homeful\Common\Traits\EnumUtils;
use Homeful\Contacts\Traits\HasCode;

enum Nationality: string
{
    use EnumUtils;
    use HasCode;

    case AFGHAN = 'Afghan';
    case ALBANIAN = 'Albanian';
    case ALGERIAN = 'Algerian';
    case AMERICAN = 'American';
    case ANDORRAN = 'Andorran';
    case ANGOLAN = 'Angolan';
    case ANGUILLAN = 'Anguillan';
    case ARGENTINE = 'Argentine';
    case ARMENIAN = 'Armenian';
    case AUSTRALIAN = 'Australian';
    case AUSTRIAN = 'Austrian';
    case AZERBAIJANI = 'Azerbaijani';
    case BAHAMIAN = 'Bahamian';
    case BAHRAINI = 'Bahraini';
    case BANGLADESHI = 'Bangladeshi';
    case BARBADIAN = 'Barbadian';
    case BELARUSIAN = 'Belarusian';
    case BELGIAN = 'Belgian';
    case BELIZEAN = 'Belizean';
    case BENINESE = 'Beninese';
    case BERMUDIAN = 'Bermudian';
    case BHUTANESE = 'Bhutanese';
    case BOLIVIAN = 'Bolivian';
    case BOTSWANAN = 'Botswanan';
    case BRAZILIAN = 'Brazilian';
    case BRITISH = 'British';
    case BRITISH_VIRGIN_ISLANDER = 'British Virgin Islander';
    case BRUNEIAN = 'Bruneian';
    case BULGARIAN = 'Bulgarian';
    case BURKINAN = 'Burkinan';
    case BURMESE = 'Burmese';
    case BURUNDIAN = 'Burundian';
    case CAMBODIAN = 'Cambodian';
    case CAMEROONIAN = 'Cameroonian';
    case CANADIAN = 'Canadian';
    case CAPE_VERDEAN = 'Cape Verdean';
    case CAYMAN_ISLANDER = 'Cayman Islander';
    case CENTRAL_AFRICAN = 'Central African';
    case CHADIAN = 'Chadian';
    case CHILEAN = 'Chilean';
    case CHINESE = 'Chinese';
    case CITIZEN_OF_ANTIGUA_BARBUDA = 'Citizen of Antigua and Barbuda';
    case CITIZEN_OF_BOSNIA_HERZEGOVINA = 'Citizen of Bosnia and Herzegovina';
    case CITIZEN_OF_GUINEA_BISSAU = 'Citizen of Guinea-Bissau';
    case CITIZEN_OF_KIRIBATI = 'Citizen of Kiribati';
    case CITIZEN_OF_SEYCHELLES = 'Citizen of Seychelles';
    case CITIZEN_OF_DOMINICAN_REPUBLIC = 'Citizen of the Dominican Republic';
    case CITIZEN_OF_VANUATU = 'Citizen of Vanuatu';
    case COLOMBIAN = 'Colombian';
    case COMORAN = 'Comoran';
    case CONGOLESE_CONGO = 'Congolese (Congo)';
    case CONGOLESE_DRC = 'Congolese (DRC)';
    case COOK_ISLANDER = 'Cook Islander';
    case COSTA_RICAN = 'Costa Rican';
    case CROATIAN = 'Croatian';
    case CUBAN = 'Cuban';
    case CYMRAES = 'Cymraes';
    case CYMRO = 'Cymro';
    case CYPRIOT = 'Cypriot';
    case CZECH = 'Czech';
    case DANISH = 'Danish';
    case DJIBOUTIAN = 'Djiboutian';
    case DOMINICAN = 'Dominican';
    case DUTCH = 'Dutch';
    case EAST_TIMORESE = 'East Timorese';
    case ECUADOREAN = 'Ecuadorean';
    case EGYPTIAN = 'Egyptian';
    case EMIRATI = 'Emirati';
    case ENGLISH = 'English';
    case EQUATORIAL_GUINEAN = 'Equatorial Guinean';
    case ERITREAN = 'Eritrean';
    case ESTONIAN = 'Estonian';
    case ETHIOPIAN = 'Ethiopian';
    case FAROESE = 'Faroese';
    case FIJIAN = 'Fijian';
    case FILIPINO = 'Filipino';
    case FINNISH = 'Finnish';
    case FRENCH = 'French';
    case GABONESE = 'Gabonese';
    case GAMBIAN = 'Gambian';
    case GEORGIAN = 'Georgian';
    case GERMAN = 'German';
    case GHANAIAN = 'Ghanaian';
    case GIBRALTARIAN = 'Gibraltarian';
    case GREEK = 'Greek';
    case GREENLANDIC = 'Greenlandic';
    case GRENADIAN = 'Grenadian';
    case GUAMANIAN = 'Guamanian';
    case GUATEMALAN = 'Guatemalan';
    case GUINEAN = 'Guinean';
    case GUYANESE = 'Guyanese';
    case HAITIAN = 'Haitian';
    case HONDURAN = 'Honduran';
    case HONG_KONGER = 'Hong Konger';
    case HUNGARIAN = 'Hungarian';
    case ICELANDIC = 'Icelandic';
    case INDIAN = 'Indian';
    case INDONESIAN = 'Indonesian';
    case IRANIAN = 'Iranian';
    case IRAQI = 'Iraqi';
    case IRISH = 'Irish';
    case ISRAELI = 'Israeli';
    case ITALIAN = 'Italian';
    case IVORIAN = 'Ivorian';
    case JAMAICAN = 'Jamaican';
    case JAPANESE = 'Japanese';
    case JORDANIAN = 'Jordanian';
    case KAZAKH = 'Kazakh';
    case KENYAN = 'Kenyan';
    case KITTIITIAN = 'Kittitian';
    case KOSOVAN = 'Kosovan';
    case KUWAITI = 'Kuwaiti';
    case KYRGYZ = 'Kyrgyz';
    case LAO = 'Lao';
    case LATVIAN = 'Latvian';
    case LEBANESE = 'Lebanese';
    case LIBERIAN = 'Liberian';
    case LIBYAN = 'Libyan';
    case LIECHTENSTEIN_CITIZEN = 'Liechtenstein citizen';
    case LITHUANIAN = 'Lithuanian';
    case LUXEMBOURGER = 'Luxembourger';
    case MACANESE = 'Macanese';
    case MACEDONIAN = 'Macedonian';
    case MALAGASY = 'Malagasy';
    case MALAWIAN = 'Malawian';
    case MALAYSIAN = 'Malaysian';
    case MALDIVIAN = 'Maldivian';
    case MALIAN = 'Malian';
    case MALTESE = 'Maltese';
    case MARSHALLESE = 'Marshallese';
    case MARTINIQUAIS = 'Martiniquais';
    case MAURITANIAN = 'Mauritanian';
    case MAURITIAN = 'Mauritian';
    case MEXICAN = 'Mexican';
    case MICRONESIAN = 'Micronesian';
    case MOLDOVAN = 'Moldovan';
    case MONEGASQUE = 'Monegasque';
    case MONGOLIAN = 'Mongolian';
    case MONTENEGRIN = 'Montenegrin';
    case MONTSERRATIAN = 'Montserratian';
    case MOROCCAN = 'Moroccan';
    case MOSOTHO = 'Mosotho';
    case MOZAMBICAN = 'Mozambican';
    case NAMIBIAN = 'Namibian';
    case NAURUAN = 'Nauruan';
    case NEPALESE = 'Nepalese';
    case NEW_ZEALANDER = 'New Zealander';
    case NICARAGUAN = 'Nicaraguan';
    case NIGERIAN = 'Nigerian';
    case NIGERIEN = 'Nigerien';
    case NIUEAN = 'Niuean';
    case NORTH_KOREAN = 'North Korean';
    case NORTHERN_IRISH = 'Northern Irish';
    case NORWEGIAN = 'Norwegian';
    case OMANI = 'Omani';
    case PAKISTANI = 'Pakistani';
    case PALAUAN = 'Palauan';
    case PALESTINIAN = 'Palestinian';
    case PANAMANIAN = 'Panamanian';
    case PAPUA_NEW_GUINEAN = 'Papua New Guinean';
    case PARAGUAYAN = 'Paraguayan';
    case PERUVIAN = 'Peruvian';
    case PITCAIRN_ISLANDER = 'Pitcairn Islander';
    case POLISH = 'Polish';
    case PORTUGUESE = 'Portuguese';
    case PRYDEINIG = 'Prydeinig';
    case PUERTO_RICAN = 'Puerto Rican';
    case QATARI = 'Qatari';
    case ROMANIAN = 'Romanian';
    case RUSSIAN = 'Russian';
    case RWANDAN = 'Rwandan';
    case SALVADOREAN = 'Salvadorean';
    case SAMMARINESE = 'Sammarinese';
    case SAMOAN = 'Samoan';
    case SAO_TOMEAN = 'Sao Tomean';
    case SAUDI_ARABIAN = 'Saudi Arabian';
    case SCOTTISH = 'Scottish';
    case SENEGALISE = 'Senegalese';
    case SERBIAN = 'Serbian';
    case SIERRA_LEONEAN = 'Sierra Leonean';
    case SINGAPOREAN = 'Singaporean';
    case SLOVAK = 'Slovak';
    case SLOVENIAN = 'Slovenian';
    case SOLOMON_ISLANDER = 'Solomon Islander';
    case SOMALI = 'Somali';
    case SOUTH_AFRICAN = 'South African';
    case SOUTH_KOREAN = 'South Korean';
    case SOUTH_SUDANESE = 'South Sudanese';
    case SPANISH = 'Spanish';
    case SRI_LANKAN = 'Sri Lankan';
    case ST_HELENIAN = 'St Helenian';
    case ST_LUCIAN = 'St Lucian';
    case STATELESS = 'Stateless';
    case SUDANESE = 'Sudanese';
    case SURINAMESE = 'Surinamese';
    case SWAZI = 'Swazi';
    case SWEDISH = 'Swedish';
    case SWISS = 'Swiss';

    static function default(): self {
        return self::FILIPINO;
    }

    public function code(): string
    {
        return match ($this) {
            self::AMERICAN => '004',
            default => '076'
        };
    }
}
