<?php

namespace Homeful\Contacts\Enums;

use Homeful\Common\Traits\EnumUtils;
use Homeful\Contacts\Traits\HasCode;

enum Position: string
{
    use EnumUtils;
    use HasCode;

    case ABLE_SEAMAN = 'Able Seaman';
    case ACCOUNT_ASSOCIATE = 'Account Associate';
    case ACCOUNT_MANAGER = 'Account Manager';
    case ACCOUNT_PROCESSOR_DOCUMENTATION = 'Account Processor Documentation';
    case ACCOUNT_REPRESENTATIVE = 'Account Representative';
    case ACCOUNT_SPECIALIST = 'Account Specialist';
    case ACCOUNT_SPECIALIST_I = 'Account Specialist I';
    case ACCOUNTANT = 'Accountant';
    case ACCOUNTING_DIRECTOR = 'Accounting Director';
    case ACCOUNTING_STAFF_ASSISTANT = 'Accounting Staff/Assistant';
    case ACCOUNTS_PAYABLE_CLERK = 'Accounts Payable Clerk';
    case ACCOUNTS_RECEIVABLE_CLERK = 'Accounts Receivable Clerk';
    case ACTUARY = 'Actuary';
    case ADMIN_AIDE_III = 'Admin Aide III';
    case ADMINISTRATIVE_ASSISTANT = 'Administrative Assistant';
    case ADMINISTRATIVE_COORDINATOR = 'Administrative Coordinator';
    case ADMINISTRATIVE_OFFICER = 'Administrative Officer';
    case ADMINISTRATIVE_SERVICES_AIDE = 'Administrative Services Aide';
    case ADMINISTRATIVE_STAFF_ASSISTANT = 'Administrative Staff/Assistant';
    case ADMINISTRATOR = 'Administrator';
    case AESTHETIC_NURSE = 'Aesthetic Nurse';
    case AESTHETICIAN = 'Aesthetician';
    case ANALYST = 'Analyst';
    case ARBITRATOR = 'Arbitrator';
    case AREA_SUPERVISOR = 'Area Supervisor';
    case ASSISTANT_MANAGER = 'Assistant Manager';
    case ASSISTANT_RESTAURANT_MANAGER = 'Assistant Restaurant Manager';
    case ASSISTANT_STORE_MANAGER = 'Assistant Store Manager';
    case ASSISTANT_SUPERVISOR = 'Assistant Supervisor';
    case ASSISTANT_TO_THE_HOSPITAL_ADMINISTRATOR = 'Assistant To The Hospital Administrator';
    case AUDIO_VISUAL = 'Audio Visual';
    case AUDITOR = 'Auditor';
    case AUTO_PAINTING_TECHNICIAN = 'Auto Painting Technician';
    case AUTOCAD_DRAFTSMAN = 'AutoCAD Draftsman';
    case AVIATION_SECURITY = 'Aviation Security';
    case BANK_TELLER = 'Bank Teller';
    case BASIC_OPERATOR = 'Basic Operator';
    case BEAUTY_ADVISOR = 'Beauty Advisor';
    case BENEFITS_ADMINISTRATOR = 'Benefits Administrator';
    case BILINGUAL_CUSTOMER_SERVICE_REPRESENTATIVE = 'Bilingual Customer Service Representative';
    case BILL_COLLECTOR = 'Bill Collector';
    case BOOKKEEPER = 'Bookkeeper';
    case BRAND_SPECIALIST = 'Brand Specialist';
    case BUDGET_ANALYST = 'Budget Analyst';
    case BUILDING_JANITOR = 'Building Janitor';
    case BUILDING_MAINTENANCE = 'Building Maintenance';
    case BUS_DRIVER = 'Bus Driver';
    case BUSINESS_DEVELOPMENT_COORDINATOR = 'Business Development Coordinator';
    case BUSINESS_REPORTER = 'Business Reporter';
    case BUTCHER = 'Butcher';
    case CADD_OPERATOR = 'CADD Operator';
    case CALL_CENTER_AGENT = 'Call Center Agent';
    case CALL_CENTER_CUSTOMER_SUPPORT = 'Call Center Customer Support';
    case CARETAKER = 'Caretaker';
    case CARPENTER = 'Carpenter';
    case CASE_MANAGER = 'Case Manager';
    case CASHIER = 'Cashier';
    case CENTER_ADMINISTRATIVE_HEAD = 'Center Administrative Head';
    case CHAPTER_SERVICE_REPRESENTATIVE = 'Chapter Service Representative';
    case CHEF_COOK = 'Chef Cook';
    case CHIEF_INSPECTORATE = 'Chief Inspectorate';
    case CIVIL_WORKER = 'Civil Worker';
    case CLEANER = 'Cleaner';
    case CLIENT_ADVISOR = 'Client Advisor';
    case COLLECTION_ANALYST = 'Collection Analyst';
    case COLLECTIONS_AGENT = 'Collections Agent';
    case COMMUNITY_EXPERT = 'Community Expert';
    case COMPANY_DRIVER = 'Company Driver';
    case COMPANY_GUARD = 'Company Guard';
    case CONDO_CLEANER = 'Condo Cleaner';
    case CONTACT_CENTER_ASSOCIATE = 'Contact Center Associate';
    case CONTENT_MANAGER = 'Content Manager';
    case CONTENT_MODERATOR = 'Content Moderator';
    case CONTROL_TOWER_ASSISTANT = 'Control Tower Assistant';
    case CONTROLLER = 'Controller';
    case CORPORATE_ATTORNEY = 'Corporate Attorney';
    case CORPORATE_DRIVER = 'Corporate Driver';
    case CUSTOMER_CARE_CONSULTANT = 'Customer Care Consultant';
    case CUSTOMER_SERVICE_REPRESENTATIVE = 'Customer Service Representative';
    case COUNCILOR = 'Councilor';
    case CREDIT_ANALYST = 'Credit Analyst';
    case CREDIT_AND_COLLECTION_ASSISTANT = 'Credit And Collection Assistant';
    case CREDIT_AND_COLLECTION_MANAGER = 'Credit And Collection Manager';
    case CREDIT_AND_COLLECTION_SPECIALIST = 'Credit And Collection Specialist';
    case CREDIT_AND_COLLECTION_SUPERVISOR = 'Credit And Collection Supervisor';
    case CUSTOMER_RELATIONSHIP_COORDINATOR = 'Customer Relationship Coordinator';
    case CUSTOMER_SERVICE_AGENT = 'Customer Service Agent';
    case CUSTOMER_SERVICE_ASSISTANT = 'Customer Service Assistant';
    case CUSTOMER_SERVICE_ASSOCIATE = 'Customer Service Associate';
    case CUSTOMER_SERVICE_MANAGER = 'Customer Service Manager';
    case CUSTOMER_SERVICE_OFFICER = 'Customer Service Officer';
    case CUSTOMER_SERVICE_SPECIALIST = 'Customer Service Specialist';
    case CUSTOMER_SUPPORT_ASSOCIATE = 'Customer Support Associate';
    case CUSTOMER_SUPPORT_OFFICER = 'Customer Support Officer';
    case DATA_ANALYST = 'Data Analyst';
    case DATA_ENCODER = 'Data Encoder';
    case DATA_PROCESS_SUPPORT_TEAM_LEAD = 'Data Process Support Team Lead';
    case DELIVERY_HELPER_RIDER = 'Delivery Helper/Rider';
    case DETACHMENT_COMMANDER = 'Detachment Commander';
    case DISPATCHER_UTILITY = 'Dispatcher/Utility';
    case DOMESTIC_HELPER = 'Domestic Helper';
    case ELECTRICAL_MAINTENANCE = 'Electrical Maintenance';
    case ELECTRICIAN = 'Electrician';
    case EMBALMER = 'Embalmer';
    case ENGINEERING_MAINTENANCE_AUGMENT = 'Engineering Maintenance Augment';
    case ENGINEERING_OFFICER = 'Engineering Officer';
    case EXECUTIVE = 'Executive';
    case EXECUTIVE_ASSISTANT = 'Executive Assistant';
    case EXECUTIVE_CUSTOMER_SERVICE_REPRESENTATIVE = 'Executive Customer Service Representative';
    case EXECUTIVE_OFFICE_SECRETARY = 'Executive Office Secretary';
    case EXECUTIVE_OPERATIONS = 'Executive Operations';
    case FACILITIES_COORDINATOR = 'Facilities Coordinator';
    case FACTORY_WORKER = 'Factory Worker';
    case FACULTY_STAFF = 'Faculty Staff';
    case FAMILY_DRIVER = 'Family Driver';
    case FIELD_MERCHANDISING_SUPERVISOR = 'Field Merchandising Supervisor';
    case FIELD_SUPERVISOR = 'Field Supervisor';
    case FILE_CLERK = 'File Clerk';
    case FINANCE_SPECIALIST = 'Finance Specialist';
    case FINANCIAL_ANALYST = 'Financial Analyst';
    case FINANCIAL_PLANNER = 'Financial Planner';
    case FOREMAN = 'Foreman';
    case FORKLIFT_OPERATOR = 'Forklift Operator';
    case GENERAL_COUNSEL = 'General Counsel';
    case GENERAL_FOREMAN_MECHANICAL = 'General Foreman Mechanical';
    case HEAD_OF_OPERATIONS = 'Head Of Operations';
    case HEAD_PASTOR = 'Head Pastor';
    case HEAVY_EQUIPMENT_OPERATOR = 'Heavy Equipment Operator';
    case HELP_DESK_COORDINATOR = 'Help Desk Coordinator';
    case HOUSEHOLD_SERVICE_WORKER = 'Household Service Worker';
    case HOUSEKEEPING_ATTENDANT = 'Housekeeping Attendant';
    case HOUSEKEEPING_STAFF = 'Housekeeping Staff';
    case HOUSEMAID = 'Housemaid';
    case HOUSEMAN = 'Houseman';
    case HUMAN_RESOURCE_ASSISTANT = 'Human Resource Assistant';
    case HUMAN_RESOURCE_MANAGER = 'Human Resource Manager';
    case HUMAN_RESOURCE_OFFICER = 'Human Resource Officer';
    case INSTALLER = 'Installer';
    case INSTRUCTOR = 'Instructor';
    case INVESTMENT_BANKING_ANALYST = 'Investment Banking Analyst';
    case IT_MANAGER = 'IT Manager';
    case IT_OPERATIONS_ASSOCIATE = 'IT Operations Associate';
    case IT_STAFF_PERSONNEL = 'IT Staff Personnel';
    case IT_SUPERVISOR = 'IT Supervisor';
    case JANITORIAL = 'Janitorial';
    case JUNIOR_SALES_ASSISTANT = 'Junior Sales Assistant';
    case JUNIOR_TAX_ASSOCIATE = 'Junior Tax Associate';
    case KITCHEN_HELPER = 'Kitchen Helper';
    case KITCHEN_STAFF = 'Kitchen Staff';
    case KITCHEN_SUPERVISOR = 'Kitchen Supervisor';
    case LABOR_GENERAL = 'Labor General';
    case LABORATORY_TECHNICIAN = 'Laboratory Technician';
    case LEGAL_AIDE = 'Legal Aide';
    case LEGAL_ANALYST = 'Legal Analyst';
    case LEGAL_ASSISTANT = 'Legal Assistant';
    case LEGAL_CONSULTANT = 'Legal Consultant';
    case LEGAL_SECRETARY = 'Legal Secretary';
    case LIAISON_OFFICER = 'Liason Officer';
    case LINEMAN = 'Lineman';
    case LINER_CLERK = 'Liner Clerk';
    case LOCAL_LEGISLATIVE_STAFF_OFFICER_III = 'Local Legislative Staff Officer III';
    case LOGISTICS_ASSISTANT_MANAGER = 'Logistics Assistant Manager';
    case LOGISTICS_STAFF = 'Logistics Staff';
    case MACHINE_OPERATOR_STAFF = 'Machine Operator Staff';
    case MAINTENANCE_TECHNICIAN = 'Maintenance Technician';
    case MANAGER = 'Manager';
    case MANUFACTURING_CREW = 'Manufacturing Crew';
    case MARKETING_ASSISTANT = 'Marketing Assistant';
    case MARKETING_MANAGER = 'Marketing Manager';
    case MASSAGE_THERAPIST = 'Massage Therapist';
    case MASTER_TEACHER_1 = 'Master Teacher 1';
    case MECHANIC = 'Mechanic';
    case MEDIATOR = 'Mediator';
    case MEDICAL_DOCUMENTATION_ASSOCIATE = 'Medical Documentation Associate';
    case MESSENGER = 'Messenger';
    case MIDWIFE_I = 'Midwife I';
    case NETWORK_OPERATIONS_ENGINEER = 'Network Operations Engineer';
    case NURSING_ATTENDANT = 'Nursing Attendant';
    case OFFICE_HOUSEKEEPER = 'Office Housekeeper';
    case OFFICE_STAFF_CLERK = 'Office Staff/Clerk';
    case OFFICE_SUPPORT_STAFF = 'Office Support Staff';
    case OFFICER = 'Officer';
    case OPERATION_ASSISTANT_STAFF = 'Operation Assistant/Staff';
    case OPERATION_MANAGER = 'Operation Manager';
    case OPERATIONS_ANALYST = 'Operations Analyst';
    case OPERATIONS_PERSONNEL = 'Operations Personnel';
    case OPERATOR = 'Operator';
    case PATROL_MAN = 'Patrol Man';
    case PAYROLL_ANALYST = 'Payroll Analyst';
    case PAYROLL_ASSISTANT = 'Payroll Assistant';
    case PAYROLL_MANAGER = 'Payroll Manager';
    case PHARMACIST_ASSISTANT = 'Pharmacist Assistant';
    case PLANNING_OFFICER_II = 'Planning Officer II';
    case PLUMBER = 'Plumber';
    case PRESIDENT = 'President';
    case PRINCIPAL = 'Principal';
    case PROCESS_ANALYST = 'Process Analyst';
    case PROCESS_ASSOCIATE = 'Process Associate';
    case PROCUREMENT_ASSISTANT = 'Procurement Assistant';
    case PROCUREMENT_SPECIALIST = 'Procurement Specialist';
    case PRODUCT_MANAGER = 'Product Manager';
    case PRODUCT_PROMOTER = 'Product Promoter';
    case PRODUCTION_FINISHER = 'Production Finisher';
    case PRODUCTION_OPERATOR = 'Production Operator';
    case PROGRAM_ADMINISTRATOR = 'Program Administrator';
    case PROGRAM_MANAGER = 'Program Manager';
    case PROGRAM_OFFICER = 'Program Officer';
    case PROJECT_COORDINATOR = 'Project Coordinator';
    case PROJECT_ENGINEER = 'Project Engineer';
    case PUBLIC_AREA_ATTENDANT = 'Public Area Attendant';
    case QC_SUPERVISOR = 'QC Supervisor';
    case QUALITY_ASSURANCE_AUDITOR = 'Quality Assurance Auditor';
    case QUALITY_ASSURANCE_SPECIALIST = 'Quality Assurance Specialist';
    case QUALITY_CONTROL_ASSISTANT = 'Quality Control Assistant';
    case QUALITY_CONTROL_SUPERVISOR = 'Quality Control Supervisor';
    case QUALITY_CONTROL_TECHNICIAN = 'Quality Control Technician';
    case RECEPTIONIST = 'Receptionist';
    case RECORD_ASSISTANT = 'Record Assistant';
    case REFRIGERATION_TECHNICIAN = 'Refrigeration Technician';
    case REGULATORY_ASSISTANT = 'Regulatory Assistant';
    case RISK_MANAGER = 'Risk Manager';
    case SAFETY_OFFICER = 'Safety Officer';
    case SAFETY_SUPERVISOR = 'Safety Supervisor';
    case SALES_ADVISOR_1 = 'Sales Advisor 1';
    case SALES_AGENT = 'Sales Agent';
    case SALES_AND_MARKETING_STAFF = 'Sales And Marketing Staff';
    case SALES_CLERK_STAFF = 'Sales Clerk/Staff';
    case SALES_CONSULTANT = 'Sales Consultant';
    case SALES_COORDINATOR = 'Sales Coordinator';
    case SALES_MANAGER = 'Sales Manager';
    case SALES_PROMOTER = 'Sales Promoter';
    case SALES_SUPERVISOR = 'Sales Supervisor';
    case SALES_SUPPORT_STAFF = 'Sales Support Staff';
    case SALESMAN = 'Salesman';
    case SCHOOL_DRIVER = 'School Driver';
    case SEAMAN = 'Seaman';
    case SECRETARY = 'Secretary';
    case SECURITY_OFFICER = 'Security Officer';
    case SECURITY_PERSONNEL = 'Security Personnel';
    case SENIOR_ACCOUNT_OFFICER = 'Senior Account Officer';
    case SENIOR_CREW = 'Senior Crew';
    case SENIOR_LOGISTICS_COORDINATOR = 'Senior Logistics Coordinator';
    case SENIOR_SALES_ASSOCIATE = 'Senior Sales Associate';
    case SENIOR_STYLIST = 'Senior Stylist';
    case SENIOR_TECHNICAL_ADVISOR = 'Senior Technical Advisor';
    case SERVICE_ANALYST = 'Service Analyst';
    case SERVICE_COORDINATOR = 'Service Coordinator';
    case SERVICE_CREW = 'Service Crew';
    case SERVICE_OFFICER = 'Service Officer';
    case SERVICE_OPERATIONS_TECHNICIAN = 'Service Operations Technician';
    case SERVICE_TECHNICIAN = 'Service Technician';
    case SITE_FINANCE_REPRESENTATIVE = 'Site Finance Representative';
    case SPORTS_DATA_ANALYST = 'Sports Data Analyst';
    case SPRINTER = 'Sprinter';
    case STAFF_ASSISTANT = 'Staff Assistant';
    case STAFF_MIDWIFE = 'Staff Midwife';
    case STAFF_NURSE = 'Staff Nurse';
    case STEELMAN = 'Steelman';
    case STOCK_CUSTODIAN = 'Stock Custodian';
    case STOCKMAN = 'Stockman';
    case STORE_KEEPER = 'Store Keeper';
    case SUPERVISOR = 'Supervisor';
    case SURVEILLANCE_OPERATOR = 'Surveillance Operator';
    case TEACHER = 'Teacher';
    case TEACHER_1 = 'Teacher 1';
    case TEACHER_1B = 'Teacher 1B';
    case TEACHER_II = 'Teacher II';
    case TEACHER_III = 'Teacher III';
    case TEACHER_FACULTY = 'Teacher/Faculty';
    case TEAM_CAPTAIN = 'Team Captain';
    case TEAM_LEADER = 'Team Leader';
    case TECHNICAL_ENGINEER = 'Technical Engineer';
    case TECHNICAL_FIELD_ENGINEER = 'Technical Field Engineer';
    case TECHNICAL_INTERN = 'Technical Intern';
    case TECHNICAL_SUPPORT_OPERATIONS = 'Technical Support Operations';
    case TECHNICAL_SUPPORT_REPRESENTATIVE = 'Technical Support Representative';
    case TECHNICAL_SUPPORT_SPECIALIST = 'Technical Support Specialist';
    case TECHNICIAN = 'Technician';
    case TELEMARKETER = 'Telemarketer';
    case TELESERVICES_REPRESENTATIVE = 'Teleservices Representative';
    case TIME_KEEPER = 'Time Keeper';
    case TREASURY_ASSISTANT = 'Treasury Assistant';
    case UTILITY_OFFICER = 'Utility Officer';
    case UTILITY_WORKER_II = 'Utility Worker II';
    case VICE_PRESIDENT = 'Vice President';
    case VILLAGE_MANAGER = 'Village Manager';
    case WAITER = 'Waiter';
    case WAREHOUSE_ASSISTANT_STAFF = 'Warehouse Assistant/Staff';
    case WAREHOUSE_SUPERVISOR = 'Warehouse Supervisor';
    case WELDER = 'Welder';
    case VIRTUAL_ASSISTANT = 'VIRTUAL ASSISTANT';
    case SR_SYSTEMS_ANALYST = 'SR SYSTEMS ANALYST';
    case DENTAL_TECHNICIAN = 'DENTAL TECHNICIAN';
    case DENTAL_DESIGNER = 'DENTAL DESIGNER';
    case GALLEY_UTILITY = 'Galley Utility';
    case RECORDS_AIDE_ENCODER = 'RECORDS AIDE/ENCODER';
    case IRON_WORK = 'Iron Work';
    case PASTRY_CHEF = 'Pastry Chef';

    static function default(): self {
        return self::SALESMAN;
    }

    public function code(): string
    {
        return match ($this) {
            self::ABLE_SEAMAN => '001',
            self::ACCOUNT_ASSOCIATE => '002',
            self::ACCOUNT_MANAGER => '003',
            self::ACCOUNT_PROCESSOR_DOCUMENTATION => '004',
            self::ACCOUNT_REPRESENTATIVE => '005',
            self::ACCOUNT_SPECIALIST => '006',
            self::ACCOUNT_SPECIALIST_I => '007',
            self::ACCOUNTANT => '008',
            self::ACCOUNTING_DIRECTOR => '009',
            self::ACCOUNTING_STAFF_ASSISTANT => '010',
            self::ACCOUNTS_PAYABLE_CLERK => '011',
            self::ACCOUNTS_RECEIVABLE_CLERK => '012',
            self::ACTUARY => '013',
            self::ADMIN_AIDE_III => '014',
            self::ADMINISTRATIVE_ASSISTANT => '015',
            self::ADMINISTRATIVE_COORDINATOR => '016',
            self::ADMINISTRATIVE_OFFICER => '017',
            self::ADMINISTRATIVE_SERVICES_AIDE => '018',
            self::ADMINISTRATIVE_STAFF_ASSISTANT => '019',
            self::ADMINISTRATOR => '020',
            self::AESTHETIC_NURSE => '021',
            self::AESTHETICIAN => '022',
            self::ANALYST => '023',
            self::ARBITRATOR => '024',
            self::AREA_SUPERVISOR => '025',
            self::ASSISTANT_MANAGER => '026',
            self::ASSISTANT_RESTAURANT_MANAGER => '027',
            self::ASSISTANT_STORE_MANAGER => '028',
            self::ASSISTANT_SUPERVISOR => '029',
            self::ASSISTANT_TO_THE_HOSPITAL_ADMINISTRATOR => '030',
            self::AUDIO_VISUAL => '031',
            self::AUDITOR => '032',
            self::AUTO_PAINTING_TECHNICIAN => '033',
            self::AUTOCAD_DRAFTSMAN => '034',
            self::AVIATION_SECURITY => '035',
            self::BANK_TELLER => '036',
            self::BASIC_OPERATOR => '037',
            self::BEAUTY_ADVISOR => '038',
            self::BENEFITS_ADMINISTRATOR => '039',
            self::BILINGUAL_CUSTOMER_SERVICE_REPRESENTATIVE => '040',
            self::BILL_COLLECTOR => '041',
            self::BOOKKEEPER => '042',
            self::BRAND_SPECIALIST => '043',
            self::BUDGET_ANALYST => '044',
            self::BUILDING_JANITOR => '045',
            self::BUILDING_MAINTENANCE => '046',
            self::BUS_DRIVER => '047',
            self::BUSINESS_DEVELOPMENT_COORDINATOR => '048',
            self::BUSINESS_REPORTER => '049',
            self::BUTCHER => '050',
            self::CADD_OPERATOR => '051',
            self::CALL_CENTER_AGENT => '052',
            self::CALL_CENTER_CUSTOMER_SUPPORT => '053',
            self::CARETAKER => '054',
            self::CARPENTER => '055',
            self::CASE_MANAGER => '056',
            self::CASHIER => '057',
            self::CENTER_ADMINISTRATIVE_HEAD => '058',
            self::CHAPTER_SERVICE_REPRESENTATIVE => '059',
            self::CHEF_COOK => '060',
            self::CHIEF_INSPECTORATE => '061',
            self::CIVIL_WORKER => '062',
            self::CLEANER => '063',
            self::CLIENT_ADVISOR => '064',
            self::COLLECTION_ANALYST => '065',
            self::COLLECTIONS_AGENT => '066',
            self::COMMUNITY_EXPERT => '067',
            self::COMPANY_DRIVER => '068',
            self::COMPANY_GUARD => '069',
            self::CONDO_CLEANER => '070',
            self::CONTACT_CENTER_ASSOCIATE => '071',
            self::CONTENT_MANAGER => '072',
            self::CONTENT_MODERATOR => '073',
            self::CONTROL_TOWER_ASSISTANT => '074',
            self::CONTROLLER => '075',
            self::CORPORATE_ATTORNEY => '076',
            self::CORPORATE_DRIVER => '077',
            self::CUSTOMER_CARE_CONSULTANT => '078',
            self::CUSTOMER_SERVICE_REPRESENTATIVE => '079',
            self::COUNCILOR => '080',
            self::CREDIT_ANALYST => '081',
            self::CREDIT_AND_COLLECTION_ASSISTANT => '082',
            self::CREDIT_AND_COLLECTION_MANAGER => '083',
            self::CREDIT_AND_COLLECTION_SPECIALIST => '084',
            self::CREDIT_AND_COLLECTION_SUPERVISOR => '085',
            self::CUSTOMER_RELATIONSHIP_COORDINATOR => '086',
            self::CUSTOMER_SERVICE_AGENT => '087',
            self::CUSTOMER_SERVICE_ASSISTANT => '088',
            self::CUSTOMER_SERVICE_ASSOCIATE => '089',
            self::CUSTOMER_SERVICE_MANAGER => '090',
            self::CUSTOMER_SERVICE_OFFICER => '091',
            self::CUSTOMER_SERVICE_SPECIALIST => '092',
            self::CUSTOMER_SUPPORT_ASSOCIATE => '093',
            self::CUSTOMER_SUPPORT_OFFICER => '094',
            self::DATA_ANALYST => '095',
            self::DATA_ENCODER => '096',
            self::DATA_PROCESS_SUPPORT_TEAM_LEAD => '097',
            self::DELIVERY_HELPER_RIDER => '098',
            self::DETACHMENT_COMMANDER => '099',
            self::DISPATCHER_UTILITY => '100',
            self::DOMESTIC_HELPER => '101',
            self::ELECTRICAL_MAINTENANCE => '102',
            self::ELECTRICIAN => '103',
            self::EMBALMER => '104',
            self::ENGINEERING_MAINTENANCE_AUGMENT => '105',
            self::ENGINEERING_OFFICER => '106',
            self::EXECUTIVE => '107',
            self::EXECUTIVE_ASSISTANT => '108',
            self::EXECUTIVE_CUSTOMER_SERVICE_REPRESENTATIVE => '109',
            self::EXECUTIVE_OFFICE_SECRETARY => '110',
            self::EXECUTIVE_OPERATIONS => '111',
            self::FACILITIES_COORDINATOR => '112',
            self::FACTORY_WORKER => '113',
            self::FACULTY_STAFF => '114',
            self::FAMILY_DRIVER => '115',
            self::FIELD_MERCHANDISING_SUPERVISOR => '116',
            self::FIELD_SUPERVISOR => '117',
            self::FILE_CLERK => '118',
            self::FINANCE_SPECIALIST => '119',
            self::FINANCIAL_ANALYST => '120',
            self::FINANCIAL_PLANNER => '121',
            self::FOREMAN => '122',
            self::FORKLIFT_OPERATOR => '123',
            self::GENERAL_COUNSEL => '124',
            self::GENERAL_FOREMAN_MECHANICAL => '125',
            self::HEAD_OF_OPERATIONS => '126',
            self::HEAD_PASTOR => '127',
            self::HEAVY_EQUIPMENT_OPERATOR => '128',
            self::HELP_DESK_COORDINATOR => '129',
            self::HOUSEHOLD_SERVICE_WORKER => '130',
            self::HOUSEKEEPING_ATTENDANT => '131',
            self::HOUSEKEEPING_STAFF => '132',
            self::HOUSEMAID => '133',
            self::HOUSEMAN => '134',
            self::HUMAN_RESOURCE_ASSISTANT => '135',
            self::HUMAN_RESOURCE_MANAGER => '136',
            self::HUMAN_RESOURCE_OFFICER => '137',
            self::INSTALLER => '138',
            self::INSTRUCTOR => '139',
            self::INVESTMENT_BANKING_ANALYST => '140',
            self::IT_MANAGER => '141',
            self::IT_OPERATIONS_ASSOCIATE => '142',
            self::IT_STAFF_PERSONNEL => '143',
            self::IT_SUPERVISOR => '144',
            self::JANITORIAL => '145',
            self::JUNIOR_SALES_ASSISTANT => '146',
            self::JUNIOR_TAX_ASSOCIATE => '147',
            self::KITCHEN_HELPER => '148',
            self::KITCHEN_STAFF => '149',
            self::KITCHEN_SUPERVISOR => '150',
            self::LABOR_GENERAL => '151',
            self::LABORATORY_TECHNICIAN => '152',
            self::LEGAL_AIDE => '153',
            self::LEGAL_ANALYST => '154',
            self::LEGAL_ASSISTANT => '155',
            self::LEGAL_CONSULTANT => '156',
            self::LEGAL_SECRETARY => '157',
            self::LIAISON_OFFICER => '158',
            self::LINEMAN => '159',
            self::LINER_CLERK => '160',
            self::LOCAL_LEGISLATIVE_STAFF_OFFICER_III => '161',
            self::LOGISTICS_ASSISTANT_MANAGER => '162',
            self::LOGISTICS_STAFF => '163',
            self::MACHINE_OPERATOR_STAFF => '164',
            self::MAINTENANCE_TECHNICIAN => '165',
            self::MANAGER => '166',
            self::MANUFACTURING_CREW => '167',
            self::MARKETING_ASSISTANT => '168',
            self::MARKETING_MANAGER => '169',
            self::MASSAGE_THERAPIST => '170',
            self::MASTER_TEACHER_1 => '171',
            self::MECHANIC => '172',
            self::MEDIATOR => '173',
            self::MEDICAL_DOCUMENTATION_ASSOCIATE => '174',
            self::MESSENGER => '175',
            self::MIDWIFE_I => '176',
            self::NETWORK_OPERATIONS_ENGINEER => '177',
            self::NURSING_ATTENDANT => '178',
            self::OFFICE_HOUSEKEEPER => '179',
            self::OFFICE_STAFF_CLERK => '180',
            self::OFFICE_SUPPORT_STAFF => '181',
            self::OFFICER => '182',
            self::OPERATION_ASSISTANT_STAFF => '183',
            self::OPERATION_MANAGER => '184',
            self::OPERATIONS_ANALYST => '185',
            self::OPERATIONS_PERSONNEL => '186',
            self::OPERATOR => '187',
            self::PATROL_MAN => '188',
            self::PAYROLL_ANALYST => '189',
            self::PAYROLL_ASSISTANT => '190',
            self::PAYROLL_MANAGER => '191',
            self::PHARMACIST_ASSISTANT => '192',
            self::PLANNING_OFFICER_II => '193',
            self::PLUMBER => '194',
            self::PRESIDENT => '195',
            self::PRINCIPAL => '196',
            self::PROCESS_ANALYST => '197',
            self::PROCESS_ASSOCIATE => '198',
            self::PROCUREMENT_ASSISTANT => '199',
            self::PROCUREMENT_SPECIALIST => '200',
            self::PRODUCT_MANAGER => '201',
            self::PRODUCT_PROMOTER => '202',
            self::PRODUCTION_FINISHER => '203',
            self::PRODUCTION_OPERATOR => '204',
            self::PROGRAM_ADMINISTRATOR => '205',
            self::PROGRAM_MANAGER => '206',
            self::PROGRAM_OFFICER => '207',
            self::PROJECT_COORDINATOR => '208',
            self::PROJECT_ENGINEER => '209',
            self::PUBLIC_AREA_ATTENDANT => '210',
            self::QC_SUPERVISOR => '211',
            self::QUALITY_ASSURANCE_AUDITOR => '212',
            self::QUALITY_ASSURANCE_SPECIALIST => '213',
            self::QUALITY_CONTROL_ASSISTANT => '214',
            self::QUALITY_CONTROL_SUPERVISOR => '215',
            self::QUALITY_CONTROL_TECHNICIAN => '216',
            self::RECEPTIONIST => '217',
            self::RECORD_ASSISTANT => '218',
            self::REFRIGERATION_TECHNICIAN => '219',
            self::REGULATORY_ASSISTANT => '220',
            self::RISK_MANAGER => '221',
            self::SAFETY_OFFICER => '222',
            self::SAFETY_SUPERVISOR => '223',
            self::SALES_ADVISOR_1 => '224',
            self::SALES_AGENT => '225',
            self::SALES_AND_MARKETING_STAFF => '226',
            self::SALES_CLERK_STAFF => '227',
            self::SALES_CONSULTANT => '228',
            self::SALES_COORDINATOR => '229',
            self::SALES_MANAGER => '230',
            self::SALES_PROMOTER => '231',
            self::SALES_SUPERVISOR => '232',
            self::SALES_SUPPORT_STAFF => '233',
            self::SALESMAN => '234',
            self::SCHOOL_DRIVER => '235',
            self::SEAMAN => '236',
            self::SECRETARY => '237',
            self::SECURITY_OFFICER => '238',
            self::SECURITY_PERSONNEL => '239',
            self::SENIOR_ACCOUNT_OFFICER => '240',
            self::SENIOR_CREW => '241',
            self::SENIOR_LOGISTICS_COORDINATOR => '242',
            self::SENIOR_SALES_ASSOCIATE => '243',
            self::SENIOR_STYLIST => '244',
            self::SENIOR_TECHNICAL_ADVISOR => '245',
            self::SERVICE_ANALYST => '246',
            self::SERVICE_COORDINATOR => '247',
            self::SERVICE_CREW => '248',
            self::SERVICE_OFFICER => '249',
            self::SERVICE_OPERATIONS_TECHNICIAN => '250',
            self::SERVICE_TECHNICIAN => '251',
            self::SITE_FINANCE_REPRESENTATIVE => '252',
            self::SPORTS_DATA_ANALYST => '253',
            self::SPRINTER => '254',
            self::STAFF_ASSISTANT => '255',
            self::STAFF_MIDWIFE => '256',
            self::STAFF_NURSE => '257',
            self::STEELMAN => '258',
            self::STOCK_CUSTODIAN => '259',
            self::STOCKMAN => '260',
            self::STORE_KEEPER => '261',
            self::SUPERVISOR => '262',
            self::SURVEILLANCE_OPERATOR => '263',
            self::TEACHER => '264',
            self::TEACHER_1 => '265',
            self::TEACHER_1B => '266',
            self::TEACHER_II => '267',
            self::TEACHER_III => '268',
            self::TEACHER_FACULTY => '269',
            self::TEAM_CAPTAIN => '270',
            self::TEAM_LEADER => '271',
            self::TECHNICAL_ENGINEER => '272',
            self::TECHNICAL_FIELD_ENGINEER => '273',
            self::TECHNICAL_INTERN => '274',
            self::TECHNICAL_SUPPORT_OPERATIONS => '275',
            self::TECHNICAL_SUPPORT_REPRESENTATIVE => '276',
            self::TECHNICAL_SUPPORT_SPECIALIST => '277',
            self::TECHNICIAN => '278',
            self::TELEMARKETER => '279',
            self::TELESERVICES_REPRESENTATIVE => '280',
            self::TIME_KEEPER => '281',
            self::TREASURY_ASSISTANT => '282',
            self::UTILITY_OFFICER => '283',
            self::UTILITY_WORKER_II => '284',
            self::VICE_PRESIDENT => '285',
            self::VILLAGE_MANAGER => '286',
            self::WAITER => '287',
            self::WAREHOUSE_ASSISTANT_STAFF => '288',
            self::WAREHOUSE_SUPERVISOR => '289',
            self::WELDER => '290',
            self::VIRTUAL_ASSISTANT => '291',
            self::SR_SYSTEMS_ANALYST => '292',
            self::DENTAL_TECHNICIAN => '293',
            self::DENTAL_DESIGNER => '294',
            self::GALLEY_UTILITY => '295',
            self::RECORDS_AIDE_ENCODER => '296',
            self::IRON_WORK => '297',
            self::PASTRY_CHEF => '298',
        };
    }
}
